### ISSUE TITLE
data

### ISSUE THREAD

**Issue by abudukeyumu** [SapienzaNLP/maverick-coref#4]
Hello, if it is convenient, can you provide the data set files used in the paper? Thank you very much.

**Comment by g185** [comment]
Hi @abudukeyumu,
Regarding OntoNotes, I cannot provide the dataset files since it is covered by license, but you can ask for access at the following link: https://catalog.ldc.upenn.edu/LDC2013T19

While the other datasets can be found online here:
- PreCo: https://drive.google.com/file/d/1q0oMt1Ynitsww9GkuhuwNZNq6SjByu-Y/view
- LitBank: https://github.com/dbamman/litbank/tree/master/coref/conll
- WikiCoref: http://rali.iro.umontreal.ca/rali/?q=en/wikicoref
they usually require some heavy preprocessing to obtain the OntoNotes-like jsonlines ready-to-use version.

I processed the following dataset and share the jsonlines version at this link: https://drive.google.com/drive/u/3/folders/18dtd1Qt4h7vezlm2G0hF72aqFcAEFCUo

N.B. for PreCo, to be comparable with previous models, we use the dev for testing and the last 500 training samples for validation.

**Comment by amith-ananthram** [comment]
Hi @g185, thanks for the great work -- would you mind specifying which Ontonotes annotation release (v4 or v12, as described here: https://cemantix.org/data/ontonotes.html) you used for training?  Thanks!

**Comment by amith-ananthram** [comment]
Actually it seems like the coreference annotations are the same in both so nevermind!
